"""create rural producer table

Revision ID: 23cfc607a0f9
Revises: 2fe5565b22e9
Create Date: 2025-06-06 15:18:16.053991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23cfc607a0f9'
down_revision: Union[str, None] = '2fe5565b22e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rural_producers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('document', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("document_type IN ('CPF', 'CNPJ')", name='chk_document_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rural_producers')
    # ### end Alembic commands ###
